//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WsdlDuplicateName.SalesItemService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class wsRevenueCenter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int extIdField;
        
        private bool groupLevelField;
        
        private string revenueCenterNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int extId {
            get {
                return this.extIdField;
            }
            set {
                this.extIdField = value;
                this.RaisePropertyChanged("extId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool groupLevel {
            get {
                return this.groupLevelField;
            }
            set {
                this.groupLevelField = value;
                this.RaisePropertyChanged("groupLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string revenueCenterName {
            get {
                return this.revenueCenterNameField;
            }
            set {
                this.revenueCenterNameField = value;
                this.RaisePropertyChanged("revenueCenterName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService", ConfigurationName="SalesItemService.SalesService")]
    public interface SalesService {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WsdlDuplicateName.SalesItemService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WsdlDuplicateName.SalesItemService.getRVCsResponse getRVCs(WsdlDuplicateName.SalesItemService.getRVCs request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        string sayHello();
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WsdlDuplicateName.SalesItemService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WsdlDuplicateName.SalesItemService.getSalesItemsV3Response getSalesItemsV3(WsdlDuplicateName.SalesItemService.getSalesItemsV3 request);
        
        // CODEGEN: Parameter 'sales' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WsdlDuplicateName.SalesItemService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WsdlDuplicateName.SalesItemService.setSalesItemsResponse setSalesItems(WsdlDuplicateName.SalesItemService.setSalesItems request);
        
        // CODEGEN: Parameter 'sales' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WsdlDuplicateName.SalesItemService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WsdlDuplicateName.SalesItemService.setSalesItemsV3Response setSalesItemsV3(WsdlDuplicateName.SalesItemService.setSalesItemsV3 request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlArrayAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(WsdlDuplicateName.SalesItemService.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WsdlDuplicateName.SalesItemService.getSalesCatsResponse getSalesCats(WsdlDuplicateName.SalesItemService.getSalesCats request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRVCs", WrapperNamespace="http://services.hotschedules.com/api/services/SalesService", IsWrapped=true)]
    public partial class getRVCs {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int concept;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int storeNum;
        
        public getRVCs() {
        }
        
        public getRVCs(int concept, int storeNum) {
            this.concept = concept;
            this.storeNum = storeNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getRVCsResponse", WrapperNamespace="http://services.hotschedules.com/api/services/SalesService", IsWrapped=true)]
    public partial class getRVCsResponse {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://services.hotschedules.com/api/services/SalesService", Order = 0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WsdlDuplicateName.SalesItemService.wsRevenueCenter[] @return;
        
        public getRVCsResponse() {
        }
        
        public getRVCsResponse(WsdlDuplicateName.SalesItemService.wsRevenueCenter[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class hsSimpleDate : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int dayField;
        
        private int monthField;
        
        private int yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
                this.RaisePropertyChanged("day");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
                this.RaisePropertyChanged("month");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class wsSalesItem3 : dataSalesItem {
        
        private hsSimpleDate businessDateField;
        
        private hsSimpleDate transDateField;
        
        private hsSimpleTime transTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public hsSimpleDate businessDate {
            get {
                return this.businessDateField;
            }
            set {
                this.businessDateField = value;
                this.RaisePropertyChanged("businessDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public hsSimpleDate transDate {
            get {
                return this.transDateField;
            }
            set {
                this.transDateField = value;
                this.RaisePropertyChanged("transDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public hsSimpleTime transTime {
            get {
                return this.transTimeField;
            }
            set {
                this.transTimeField = value;
                this.RaisePropertyChanged("transTime");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class hsSimpleTime : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string amPmField;
        
        private int hoursField;
        
        private bool militaryTimeField;
        
        private int minutesField;
        
        private int secondsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string amPm {
            get {
                return this.amPmField;
            }
            set {
                this.amPmField = value;
                this.RaisePropertyChanged("amPm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int hours {
            get {
                return this.hoursField;
            }
            set {
                this.hoursField = value;
                this.RaisePropertyChanged("hours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool militaryTime {
            get {
                return this.militaryTimeField;
            }
            set {
                this.militaryTimeField = value;
                this.RaisePropertyChanged("militaryTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int minutes {
            get {
                return this.minutesField;
            }
            set {
                this.minutesField = value;
                this.RaisePropertyChanged("minutes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
                this.RaisePropertyChanged("seconds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsSalesItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsSalesItem3))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public abstract partial class dataSalesItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string catNameField;
        
        private int clientIdField;
        
        private int empIdField;
        
        private int extIdField;
        
        private int rvcField;
        
        private string rvcNameField;
        
        private int salesCatField;
        
        private int storeNumField;
        
        private float ttlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string catName {
            get {
                return this.catNameField;
            }
            set {
                this.catNameField = value;
                this.RaisePropertyChanged("catName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int clientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
                this.RaisePropertyChanged("clientId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int empId {
            get {
                return this.empIdField;
            }
            set {
                this.empIdField = value;
                this.RaisePropertyChanged("empId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int extId {
            get {
                return this.extIdField;
            }
            set {
                this.extIdField = value;
                this.RaisePropertyChanged("extId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int rvc {
            get {
                return this.rvcField;
            }
            set {
                this.rvcField = value;
                this.RaisePropertyChanged("rvc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string rvcName {
            get {
                return this.rvcNameField;
            }
            set {
                this.rvcNameField = value;
                this.RaisePropertyChanged("rvcName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int salesCat {
            get {
                return this.salesCatField;
            }
            set {
                this.salesCatField = value;
                this.RaisePropertyChanged("salesCat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int storeNum {
            get {
                return this.storeNumField;
            }
            set {
                this.storeNumField = value;
                this.RaisePropertyChanged("storeNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public float ttl {
            get {
                return this.ttlField;
            }
            set {
                this.ttlField = value;
                this.RaisePropertyChanged("ttl");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class wsSalesItem : dataSalesItem {
        
        private System.DateTime businessDateField;
        
        private bool businessDateFieldSpecified;
        
        private System.DateTime dateTimeField;
        
        private bool dateTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime businessDate {
            get {
                return this.businessDateField;
            }
            set {
                this.businessDateField = value;
                this.RaisePropertyChanged("businessDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool businessDateSpecified {
            get {
                return this.businessDateFieldSpecified;
            }
            set {
                this.businessDateFieldSpecified = value;
                this.RaisePropertyChanged("businessDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
                this.RaisePropertyChanged("dateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateTimeSpecified {
            get {
                return this.dateTimeFieldSpecified;
            }
            set {
                this.dateTimeFieldSpecified = value;
                this.RaisePropertyChanged("dateTimeSpecified");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSalesItemsV3", WrapperNamespace="http://services.hotschedules.com/api/services/SalesService", IsWrapped=true)]
    public partial class getSalesItemsV3 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int concept;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int storeNum;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://services.hotschedules.com/api/services/SalesService", Order = 2)]
        public WsdlDuplicateName.SalesItemService.hsSimpleDate start;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://services.hotschedules.com/api/services/SalesService", Order = 3)]
        public WsdlDuplicateName.SalesItemService.hsSimpleDate end;
        
        public getSalesItemsV3() {
        }
        
        public getSalesItemsV3(int concept, int storeNum, WsdlDuplicateName.SalesItemService.hsSimpleDate start, WsdlDuplicateName.SalesItemService.hsSimpleDate end) {
            this.concept = concept;
            this.storeNum = storeNum;
            this.start = start;
            this.end = end;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSalesItemsV3Response", WrapperNamespace="http://services.hotschedules.com/api/services/SalesService", IsWrapped=true)]
    public partial class getSalesItemsV3Response {

        [System.ServiceModel.MessageBodyMemberAttribute(Order = 0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WsdlDuplicateName.SalesItemService.wsSalesItem3[] @return;
        
        public getSalesItemsV3Response() {
        }
        
        public getSalesItemsV3Response(WsdlDuplicateName.SalesItemService.wsSalesItem3[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class wsReturn : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] errorsField;
        
        private int failCountField;
        
        private bool successField;
        
        private int successCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public string[] errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
                this.RaisePropertyChanged("errors");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int failCount {
            get {
                return this.failCountField;
            }
            set {
                this.failCountField = value;
                this.RaisePropertyChanged("failCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int successCount {
            get {
                return this.successCountField;
            }
            set {
                this.successCountField = value;
                this.RaisePropertyChanged("successCount");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setSalesItems", WrapperNamespace="http://services.hotschedules.com/api/services/SalesService", IsWrapped=true)]
    public partial class setSalesItems {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int concept;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int storeNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WsdlDuplicateName.SalesItemService.wsSalesItem[] sales;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=3)]
        public System.DateTime start;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=4)]
        public System.DateTime end;
        
        public setSalesItems() {
        }
        
        public setSalesItems(int concept, int storeNum, WsdlDuplicateName.SalesItemService.wsSalesItem[] sales, System.DateTime start, System.DateTime end) {
            this.concept = concept;
            this.storeNum = storeNum;
            this.sales = sales;
            this.start = start;
            this.end = end;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setSalesItemsResponse", WrapperNamespace="http://services.hotschedules.com/api/services/SalesService", IsWrapped=true)]
    public partial class setSalesItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Order=0)]
        public WsdlDuplicateName.SalesItemService.wsReturn @return;
        
        public setSalesItemsResponse() {
        }
        
        public setSalesItemsResponse(WsdlDuplicateName.SalesItemService.wsReturn @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setSalesItemsV3", WrapperNamespace="http://services.hotschedules.com/api/services/SalesService", IsWrapped=true)]
    public partial class setSalesItemsV3 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int concept;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int storeNum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=2)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WsdlDuplicateName.SalesItemService.wsSalesItem3[] sales;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://services.hotschedules.com/api/services/SalesService", Order = 3)]
        public WsdlDuplicateName.SalesItemService.hsSimpleDate start;

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://services.hotschedules.com/api/services/SalesService", Order = 4)]
        public WsdlDuplicateName.SalesItemService.hsSimpleDate end;
        
        public setSalesItemsV3() {
        }
        
        public setSalesItemsV3(int concept, int storeNum, WsdlDuplicateName.SalesItemService.wsSalesItem3[] sales, WsdlDuplicateName.SalesItemService.hsSimpleDate start, WsdlDuplicateName.SalesItemService.hsSimpleDate end) {
            this.concept = concept;
            this.storeNum = storeNum;
            this.sales = sales;
            this.start = start;
            this.end = end;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="setSalesItemsV3Response", WrapperNamespace="http://services.hotschedules.com/api/services/SalesService", IsWrapped=true)]
    public partial class setSalesItemsV3Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Order=0)]
        public WsdlDuplicateName.SalesItemService.wsReturn @return;
        
        public setSalesItemsV3Response() {
        }
        
        public setSalesItemsV3Response(WsdlDuplicateName.SalesItemService.wsReturn @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class wsSalesCategory : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int extIdField;
        
        private bool groupLevelField;
        
        private string salesCategoryNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int extId {
            get {
                return this.extIdField;
            }
            set {
                this.extIdField = value;
                this.RaisePropertyChanged("extId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool groupLevel {
            get {
                return this.groupLevelField;
            }
            set {
                this.groupLevelField = value;
                this.RaisePropertyChanged("groupLevel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string salesCategoryName {
            get {
                return this.salesCategoryNameField;
            }
            set {
                this.salesCategoryNameField = value;
                this.RaisePropertyChanged("salesCategoryName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSalesCats", WrapperNamespace="http://services.hotschedules.com/api/services/SalesService", IsWrapped=true)]
    public partial class getSalesCats {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public int concept;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public int storeNum;
        
        public getSalesCats() {
        }
        
        public getSalesCats(int concept, int storeNum) {
            this.concept = concept;
            this.storeNum = storeNum;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSalesCatsResponse", WrapperNamespace="http://services.hotschedules.com/api/services/SalesService", IsWrapped=true)]
    public partial class getSalesCatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute()]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public WsdlDuplicateName.SalesItemService.wsSalesCategory[] @return;
        
        public getSalesCatsResponse() {
        }
        
        public getSalesCatsResponse(WsdlDuplicateName.SalesItemService.wsSalesCategory[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SalesServiceChannel : WsdlDuplicateName.SalesItemService.SalesService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SalesServiceClient : System.ServiceModel.ClientBase<WsdlDuplicateName.SalesItemService.SalesService>, WsdlDuplicateName.SalesItemService.SalesService {
        
        public SalesServiceClient() {
        }
        
        public SalesServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SalesServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SalesServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsdlDuplicateName.SalesItemService.getRVCsResponse WsdlDuplicateName.SalesItemService.SalesService.getRVCs(WsdlDuplicateName.SalesItemService.getRVCs request) {
            return base.Channel.getRVCs(request);
        }
        
        public WsdlDuplicateName.SalesItemService.wsRevenueCenter[] getRVCs(int concept, int storeNum) {
            WsdlDuplicateName.SalesItemService.getRVCs inValue = new WsdlDuplicateName.SalesItemService.getRVCs();
            inValue.concept = concept;
            inValue.storeNum = storeNum;
            WsdlDuplicateName.SalesItemService.getRVCsResponse retVal = ((WsdlDuplicateName.SalesItemService.SalesService)(this)).getRVCs(inValue);
            return retVal.@return;
        }
        
        public string sayHello() {
            return base.Channel.sayHello();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsdlDuplicateName.SalesItemService.getSalesItemsV3Response WsdlDuplicateName.SalesItemService.SalesService.getSalesItemsV3(WsdlDuplicateName.SalesItemService.getSalesItemsV3 request) {
            return base.Channel.getSalesItemsV3(request);
        }
        
        public WsdlDuplicateName.SalesItemService.wsSalesItem3[] getSalesItemsV3(int concept, int storeNum, WsdlDuplicateName.SalesItemService.hsSimpleDate start, WsdlDuplicateName.SalesItemService.hsSimpleDate end) {
            WsdlDuplicateName.SalesItemService.getSalesItemsV3 inValue = new WsdlDuplicateName.SalesItemService.getSalesItemsV3();
            inValue.concept = concept;
            inValue.storeNum = storeNum;
            inValue.start = start;
            inValue.end = end;
            WsdlDuplicateName.SalesItemService.getSalesItemsV3Response retVal = ((WsdlDuplicateName.SalesItemService.SalesService)(this)).getSalesItemsV3(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsdlDuplicateName.SalesItemService.setSalesItemsResponse WsdlDuplicateName.SalesItemService.SalesService.setSalesItems(WsdlDuplicateName.SalesItemService.setSalesItems request) {
            return base.Channel.setSalesItems(request);
        }
        
        public WsdlDuplicateName.SalesItemService.wsReturn setSalesItems(int concept, int storeNum, WsdlDuplicateName.SalesItemService.wsSalesItem[] sales, System.DateTime start, System.DateTime end) {
            WsdlDuplicateName.SalesItemService.setSalesItems inValue = new WsdlDuplicateName.SalesItemService.setSalesItems();
            inValue.concept = concept;
            inValue.storeNum = storeNum;
            inValue.sales = sales;
            inValue.start = start;
            inValue.end = end;
            WsdlDuplicateName.SalesItemService.setSalesItemsResponse retVal = ((WsdlDuplicateName.SalesItemService.SalesService)(this)).setSalesItems(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsdlDuplicateName.SalesItemService.setSalesItemsV3Response WsdlDuplicateName.SalesItemService.SalesService.setSalesItemsV3(WsdlDuplicateName.SalesItemService.setSalesItemsV3 request) {
            return base.Channel.setSalesItemsV3(request);
        }
        
        public WsdlDuplicateName.SalesItemService.wsReturn setSalesItemsV3(int concept, int storeNum, WsdlDuplicateName.SalesItemService.wsSalesItem3[] sales, WsdlDuplicateName.SalesItemService.hsSimpleDate start, WsdlDuplicateName.SalesItemService.hsSimpleDate end) {
            WsdlDuplicateName.SalesItemService.setSalesItemsV3 inValue = new WsdlDuplicateName.SalesItemService.setSalesItemsV3();
            inValue.concept = concept;
            inValue.storeNum = storeNum;
            inValue.sales = sales;
            inValue.start = start;
            inValue.end = end;
            WsdlDuplicateName.SalesItemService.setSalesItemsV3Response retVal = ((WsdlDuplicateName.SalesItemService.SalesService)(this)).setSalesItemsV3(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WsdlDuplicateName.SalesItemService.getSalesCatsResponse WsdlDuplicateName.SalesItemService.SalesService.getSalesCats(WsdlDuplicateName.SalesItemService.getSalesCats request) {
            return base.Channel.getSalesCats(request);
        }
        
        public WsdlDuplicateName.SalesItemService.wsSalesCategory[] getSalesCats(int concept, int storeNum) {
            WsdlDuplicateName.SalesItemService.getSalesCats inValue = new WsdlDuplicateName.SalesItemService.getSalesCats();
            inValue.concept = concept;
            inValue.storeNum = storeNum;
            WsdlDuplicateName.SalesItemService.getSalesCatsResponse retVal = ((WsdlDuplicateName.SalesItemService.SalesService)(this)).getSalesCats(inValue);
            return retVal.@return;
        }
    }
}
