//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.34209.
// 
#pragma warning disable 1591

namespace wcf_29132014.com.hotschedules.services {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SalesItemServiceServiceSoapBinding", Namespace="http://services.hotschedules.com/api/services/SalesService")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(dataSalesItem))]
    public partial class SalesItemServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getRVCsOperationCompleted;
        
        private System.Threading.SendOrPostCallback sayHelloOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSalesItemsV3OperationCompleted;
        
        private System.Threading.SendOrPostCallback setSalesItemsOperationCompleted;
        
        private System.Threading.SendOrPostCallback setSalesItemsV3OperationCompleted;
        
        private System.Threading.SendOrPostCallback getSalesCatsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SalesItemServiceService() {
            this.Url = global::wcf_29132014.Properties.Settings.Default.wcf_29132014_com_hotschedules_services_SalesItemServiceService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getRVCsCompletedEventHandler getRVCsCompleted;
        
        /// <remarks/>
        public event sayHelloCompletedEventHandler sayHelloCompleted;
        
        /// <remarks/>
        public event getSalesItemsV3CompletedEventHandler getSalesItemsV3Completed;
        
        /// <remarks/>
        public event setSalesItemsCompletedEventHandler setSalesItemsCompleted;
        
        /// <remarks/>
        public event setSalesItemsV3CompletedEventHandler setSalesItemsV3Completed;
        
        /// <remarks/>
        public event getSalesCatsCompletedEventHandler getSalesCatsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://services.hotschedules.com/api/services/SalesService", ResponseNamespace="http://services.hotschedules.com/api/services/SalesService", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsRevenueCenter[] getRVCs(int concept, int storeNum) {
            object[] results = this.Invoke("getRVCs", new object[] {
                        concept,
                        storeNum});
            return ((wsRevenueCenter[])(results[0]));
        }
        
        /// <remarks/>
        public void getRVCsAsync(int concept, int storeNum) {
            this.getRVCsAsync(concept, storeNum, null);
        }
        
        /// <remarks/>
        public void getRVCsAsync(int concept, int storeNum, object userState) {
            if ((this.getRVCsOperationCompleted == null)) {
                this.getRVCsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRVCsOperationCompleted);
            }
            this.InvokeAsync("getRVCs", new object[] {
                        concept,
                        storeNum}, this.getRVCsOperationCompleted, userState);
        }
        
        private void OngetRVCsOperationCompleted(object arg) {
            if ((this.getRVCsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRVCsCompleted(this, new getRVCsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://services.hotschedules.com/api/services/SalesService", ResponseNamespace="http://services.hotschedules.com/api/services/SalesService", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public string sayHello() {
            object[] results = this.Invoke("sayHello", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sayHelloAsync() {
            this.sayHelloAsync(null);
        }
        
        /// <remarks/>
        public void sayHelloAsync(object userState) {
            if ((this.sayHelloOperationCompleted == null)) {
                this.sayHelloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsayHelloOperationCompleted);
            }
            this.InvokeAsync("sayHello", new object[0], this.sayHelloOperationCompleted, userState);
        }
        
        private void OnsayHelloOperationCompleted(object arg) {
            if ((this.sayHelloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sayHelloCompleted(this, new sayHelloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://services.hotschedules.com/api/services/SalesService", ResponseNamespace="http://services.hotschedules.com/api/services/SalesService", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsSalesItem3[] getSalesItemsV3(int concept, int storeNum, hsSimpleDate start, hsSimpleDate end) {
            object[] results = this.Invoke("getSalesItemsV3", new object[] {
                        concept,
                        storeNum,
                        start,
                        end});
            return ((wsSalesItem3[])(results[0]));
        }
        
        /// <remarks/>
        public void getSalesItemsV3Async(int concept, int storeNum, hsSimpleDate start, hsSimpleDate end) {
            this.getSalesItemsV3Async(concept, storeNum, start, end, null);
        }
        
        /// <remarks/>
        public void getSalesItemsV3Async(int concept, int storeNum, hsSimpleDate start, hsSimpleDate end, object userState) {
            if ((this.getSalesItemsV3OperationCompleted == null)) {
                this.getSalesItemsV3OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSalesItemsV3OperationCompleted);
            }
            this.InvokeAsync("getSalesItemsV3", new object[] {
                        concept,
                        storeNum,
                        start,
                        end}, this.getSalesItemsV3OperationCompleted, userState);
        }
        
        private void OngetSalesItemsV3OperationCompleted(object arg) {
            if ((this.getSalesItemsV3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSalesItemsV3Completed(this, new getSalesItemsV3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://services.hotschedules.com/api/services/SalesService", ResponseNamespace="http://services.hotschedules.com/api/services/SalesService", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public wsReturn setSalesItems(int concept, int storeNum, [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] wsSalesItem[] sales, System.DateTime start, System.DateTime end) {
            object[] results = this.Invoke("setSalesItems", new object[] {
                        concept,
                        storeNum,
                        sales,
                        start,
                        end});
            return ((wsReturn)(results[0]));
        }
        
        /// <remarks/>
        public void setSalesItemsAsync(int concept, int storeNum, wsSalesItem[] sales, System.DateTime start, System.DateTime end) {
            this.setSalesItemsAsync(concept, storeNum, sales, start, end, null);
        }
        
        /// <remarks/>
        public void setSalesItemsAsync(int concept, int storeNum, wsSalesItem[] sales, System.DateTime start, System.DateTime end, object userState) {
            if ((this.setSalesItemsOperationCompleted == null)) {
                this.setSalesItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetSalesItemsOperationCompleted);
            }
            this.InvokeAsync("setSalesItems", new object[] {
                        concept,
                        storeNum,
                        sales,
                        start,
                        end}, this.setSalesItemsOperationCompleted, userState);
        }
        
        private void OnsetSalesItemsOperationCompleted(object arg) {
            if ((this.setSalesItemsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setSalesItemsCompleted(this, new setSalesItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://services.hotschedules.com/api/services/SalesService", ResponseNamespace="http://services.hotschedules.com/api/services/SalesService", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlElementAttribute("return")]
        public wsReturn setSalesItemsV3(int concept, int storeNum, [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] wsSalesItem3[] sales, hsSimpleDate start, hsSimpleDate end) {
            object[] results = this.Invoke("setSalesItemsV3", new object[] {
                        concept,
                        storeNum,
                        sales,
                        start,
                        end});
            return ((wsReturn)(results[0]));
        }
        
        /// <remarks/>
        public void setSalesItemsV3Async(int concept, int storeNum, wsSalesItem3[] sales, hsSimpleDate start, hsSimpleDate end) {
            this.setSalesItemsV3Async(concept, storeNum, sales, start, end, null);
        }
        
        /// <remarks/>
        public void setSalesItemsV3Async(int concept, int storeNum, wsSalesItem3[] sales, hsSimpleDate start, hsSimpleDate end, object userState) {
            if ((this.setSalesItemsV3OperationCompleted == null)) {
                this.setSalesItemsV3OperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetSalesItemsV3OperationCompleted);
            }
            this.InvokeAsync("setSalesItemsV3", new object[] {
                        concept,
                        storeNum,
                        sales,
                        start,
                        end}, this.setSalesItemsV3OperationCompleted, userState);
        }
        
        private void OnsetSalesItemsV3OperationCompleted(object arg) {
            if ((this.setSalesItemsV3Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setSalesItemsV3Completed(this, new setSalesItemsV3CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://services.hotschedules.com/api/services/SalesService", ResponseNamespace="http://services.hotschedules.com/api/services/SalesService", Use=System.Web.Services.Description.SoapBindingUse.Literal)]
        [return: System.Xml.Serialization.XmlArrayAttribute("return")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public wsSalesCategory[] getSalesCats(int concept, int storeNum) {
            object[] results = this.Invoke("getSalesCats", new object[] {
                        concept,
                        storeNum});
            return ((wsSalesCategory[])(results[0]));
        }
        
        /// <remarks/>
        public void getSalesCatsAsync(int concept, int storeNum) {
            this.getSalesCatsAsync(concept, storeNum, null);
        }
        
        /// <remarks/>
        public void getSalesCatsAsync(int concept, int storeNum, object userState) {
            if ((this.getSalesCatsOperationCompleted == null)) {
                this.getSalesCatsOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSalesCatsOperationCompleted);
            }
            this.InvokeAsync("getSalesCats", new object[] {
                        concept,
                        storeNum}, this.getSalesCatsOperationCompleted, userState);
        }
        
        private void OngetSalesCatsOperationCompleted(object arg) {
            if ((this.getSalesCatsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSalesCatsCompleted(this, new getSalesCatsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class wsRevenueCenter {
        
        private int extIdField;
        
        private bool groupLevelField;
        
        private string revenueCenterNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int extId {
            get {
                return this.extIdField;
            }
            set {
                this.extIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool groupLevel {
            get {
                return this.groupLevelField;
            }
            set {
                this.groupLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string revenueCenterName {
            get {
                return this.revenueCenterNameField;
            }
            set {
                this.revenueCenterNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class wsSalesCategory {
        
        private int extIdField;
        
        private bool groupLevelField;
        
        private string salesCategoryNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int extId {
            get {
                return this.extIdField;
            }
            set {
                this.extIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool groupLevel {
            get {
                return this.groupLevelField;
            }
            set {
                this.groupLevelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string salesCategoryName {
            get {
                return this.salesCategoryNameField;
            }
            set {
                this.salesCategoryNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class wsReturn {
        
        private string[] errorsField;
        
        private int failCountField;
        
        private bool successField;
        
        private int successCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("errors", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string[] errors {
            get {
                return this.errorsField;
            }
            set {
                this.errorsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int failCount {
            get {
                return this.failCountField;
            }
            set {
                this.failCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int successCount {
            get {
                return this.successCountField;
            }
            set {
                this.successCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class hsSimpleTime {
        
        private string amPmField;
        
        private int hoursField;
        
        private bool militaryTimeField;
        
        private int minutesField;
        
        private int secondsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string amPm {
            get {
                return this.amPmField;
            }
            set {
                this.amPmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int hours {
            get {
                return this.hoursField;
            }
            set {
                this.hoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool militaryTime {
            get {
                return this.militaryTimeField;
            }
            set {
                this.militaryTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int minutes {
            get {
                return this.minutesField;
            }
            set {
                this.minutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsSalesItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(wsSalesItem3))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public abstract partial class dataSalesItem {
        
        private string catNameField;
        
        private int clientIdField;
        
        private int empIdField;
        
        private int extIdField;
        
        private int rvcField;
        
        private string rvcNameField;
        
        private int salesCatField;
        
        private int storeNumField;
        
        private float ttlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string catName {
            get {
                return this.catNameField;
            }
            set {
                this.catNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int clientId {
            get {
                return this.clientIdField;
            }
            set {
                this.clientIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int empId {
            get {
                return this.empIdField;
            }
            set {
                this.empIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int extId {
            get {
                return this.extIdField;
            }
            set {
                this.extIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int rvc {
            get {
                return this.rvcField;
            }
            set {
                this.rvcField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rvcName {
            get {
                return this.rvcNameField;
            }
            set {
                this.rvcNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int salesCat {
            get {
                return this.salesCatField;
            }
            set {
                this.salesCatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int storeNum {
            get {
                return this.storeNumField;
            }
            set {
                this.storeNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public float ttl {
            get {
                return this.ttlField;
            }
            set {
                this.ttlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class wsSalesItem : dataSalesItem {
        
        private System.DateTime businessDateField;
        
        private bool businessDateFieldSpecified;
        
        private System.DateTime dateTimeField;
        
        private bool dateTimeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime businessDate {
            get {
                return this.businessDateField;
            }
            set {
                this.businessDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool businessDateSpecified {
            get {
                return this.businessDateFieldSpecified;
            }
            set {
                this.businessDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime dateTime {
            get {
                return this.dateTimeField;
            }
            set {
                this.dateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateTimeSpecified {
            get {
                return this.dateTimeFieldSpecified;
            }
            set {
                this.dateTimeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class wsSalesItem3 : dataSalesItem {
        
        private hsSimpleDate businessDateField;
        
        private hsSimpleDate transDateField;
        
        private hsSimpleTime transTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hsSimpleDate businessDate {
            get {
                return this.businessDateField;
            }
            set {
                this.businessDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hsSimpleDate transDate {
            get {
                return this.transDateField;
            }
            set {
                this.transDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public hsSimpleTime transTime {
            get {
                return this.transTimeField;
            }
            set {
                this.transTimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.hotschedules.com/api/services/SalesService")]
    public partial class hsSimpleDate {
        
        private int dayField;
        
        private int monthField;
        
        private int yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int day {
            get {
                return this.dayField;
            }
            set {
                this.dayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getRVCsCompletedEventHandler(object sender, getRVCsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRVCsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRVCsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsRevenueCenter[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsRevenueCenter[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void sayHelloCompletedEventHandler(object sender, sayHelloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sayHelloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sayHelloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getSalesItemsV3CompletedEventHandler(object sender, getSalesItemsV3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSalesItemsV3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSalesItemsV3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsSalesItem3[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsSalesItem3[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void setSalesItemsCompletedEventHandler(object sender, setSalesItemsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setSalesItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setSalesItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void setSalesItemsV3CompletedEventHandler(object sender, setSalesItemsV3CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setSalesItemsV3CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setSalesItemsV3CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsReturn Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsReturn)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    public delegate void getSalesCatsCompletedEventHandler(object sender, getSalesCatsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSalesCatsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSalesCatsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public wsSalesCategory[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((wsSalesCategory[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591